### ISSUE TITLE
code help

### ISSUE THREAD

**Issue by Mchun-zhou** [wangzx1219/Dk-KD#1]
Hi, can you provide the complete Combiner code? 
kNN_prob, nmt_prob = self.combiner.**get_no_combined_prob**(knn_prob, teacher_output[0], log_probs=False)

**Comment by wangzx1219** [comment]
Thanks for the correction, I updated the code

**Comment by wangzx1219** [comment]
> Hi, can you provide the complete Combiner code? kNN_prob, nmt_prob = self.combiner.**get_no_combined_prob**(knn_prob, teacher_output[0], log_probs=False)

Thanks for the correction, I updated the code

**Comment by Mchun-zhou** [comment]
Hello, can you please leave your contact information? I have a question for you.

**Comment by wangzx1219** [comment]
> Hello, can you please leave your contact information? I have a question for you.
You can find my email in the paper directly.
